### PR TITLE
Change json schema

### PR DESCRIPTION
**Pull request by Szeraax**
Needs to be imported by your JSON tool and written to file. Has BOM on this UTF8 encoding for GameData files!

See updated schema (diff: https://github.com/ouya-saviors/ouya-game-data/compare/change-media-format?expand=1#diff-3562917186cf076c3b6ef65bc83ffb16 )

### CODE REVIEW

**Comment by cweiske** [comment]
Remove the BOM please. 
https://tools.ietf.org/html/rfc7159#section-8.1
> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.  In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

This is probably why the build fails with `JSON parse error: JSON_ERROR_SYNTAX`

**Comment by cweiske** [comment]
And please keep the current indentation and property order. Currently the files look like totally changed.

**Comment by cweiske** [comment]
Escaped slashes in JSON: https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped

**Comment by Szeraax** [comment]
Redoing on new master. Closing.

**Comment by Szeraax** [comment]
I'm dumb

**Comment by Szeraax** [comment]
Super dumb

**Comment by cweiske** [comment]
Thanks! merged.

**Pull request closed without merging**
