### PR TITLE
add 63 little pieces game data json

### PR DESCRIPTION
**Pull request by Omeric**

### CODE REVIEW

**Comment by cweiske** [comment]
```
classic/com.samuelsousa.littlepieces.json
JSON does not validate. Violations:
[media[0].thumb] NULL value found, but a string is required
[media[1].thumb] NULL value found, but a string is required
[media[2].thumb] NULL value found, but a string is required
[media[3].thumb] NULL value found, but a string is required
[media[4].thumb] NULL value found, but a string is required
[media[5].thumb] NULL value found, but a string is required
[media[6].thumb] NULL value found, but a string is required
[media[7].thumb] NULL value found, but a string is required
[media[8].thumb] NULL value found, but a string is required
[media[9].thumb] NULL value found, but a string is required
[media[10].thumb] NULL value found, but a string is required
```

Simply remove the "thumb" fields, they are not required. (only type and url required, see https://github.com/ouya-saviors/ouya-game-data/blob/master/ouya-game.schema.json#L182)

**Comment by Omeric** [comment]
ok

**Comment by cweiske** [comment]
@Omeric There is still one empty thumb field.

**Comment by cweiske** [comment]
Thanks - merged!

**Pull request closed without merging**
