### PR TITLE
Create com.EightBBGames.NeonFlap.json

### PR DESCRIPTION
**Pull request by Toasterkidd**

### CODE REVIEW

**Comment by cweiske** [comment]
```
new/com.EightBBGames.NeonFlap.json

JSON does not validate. Violations:

[releases[0].cert_fingerprint] Must be at least 95 characters long

[releases[0].cert_fingerprint] Does not match the regex pattern ^([0-9A-F]{2}:){31}[0-9A-F]{2}$

The command "./bin/validate-all-games.sh" exited with 23.
```

**Comment by Toasterkidd** [comment]
Removed the cert

**Comment by cweiske** [comment]
Thanks!

**Comment by cweiske** [comment]
What about the images?
The discover image is for parkouya, the others do not exist

**Comment by Toasterkidd** [comment]
Just waiting on Szereax for the images and corresponding links

**Pull request merged**
