### PR TITLE
Updating org.schabi.newpipelegacy.json 

### PR DESCRIPTION
**Pull request by ZacharyFoxx**
Updating the apk to the last version and changing the repository of the images and of the apks.

### CODE REVIEW

**Comment by cweiske** [comment]
Please rename the new apk file to include the version number.

**Comment by ZacharyFoxx** [comment]
> Please rename the new apk file to include the version number.

Hi.

Done!

Done. I already edited the json file too.

**Comment by cweiske** [comment]
I have version 18.x installed, and when I try to install the new one I get an error:
```
cweiske:~/tmp> adb install NewPipeLegacy-v0.20.8-OUYA-signed.apk 
Performing Push Install
NewPipeLegacy-v0.20.8-OUYA-signed.apk: 1 file pushed. 1.2 MB/s (8357555 bytes in 6.797s)
	pkg: /data/local/tmp/NewPipeLegacy-v0.20.8-OUYA-signed.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

Does this mean that people cannot simply update the app, but have to uninstall it and reinstall it?

**Comment by ZacharyFoxx** [comment]
> I have version 18.x installed, and when I try to install the new one I get an error:
> 
> ```
> cweiske:~/tmp> adb install NewPipeLegacy-v0.20.8-OUYA-signed.apk 
> Performing Push Install
> NewPipeLegacy-v0.20.8-OUYA-signed.apk: 1 file pushed. 1.2 MB/s (8357555 bytes in 6.797s)
> 	pkg: /data/local/tmp/NewPipeLegacy-v0.20.8-OUYA-signed.apk
> Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
> ```
> 
> Does this mean that people cannot simply update the app, but have to uninstall it and reinstall it?

Hi,

I'm sorry, but probably  yes, because the previous version wasn't signed.

I thought that I had signed, but when I used the apk which is at the archive.org to get the ouya_icon.png to the new version, i didn't find any png file. If you check the md5sum of the old version, it's same of the original version of NewPipe Legay at here: 

https://github.com/TeamNewPipe/NewPipe-legacy/releases/download/v0.18.6/NewPipeLegacy-v0.18.6.apk

I only started to sign the apks which I did pull requests after the Power Menu's pull request. Before that I didn't sign the apks.

But, is it possible have a unsigned version of the apk and a new and signed version?

**Comment by cweiske** [comment]
We can put the new signed one up, but then the description needs to warn that the old version needs to be uninstalled first.

**Comment by ZacharyFoxx** [comment]
I changed the description, including a warning.:

"description": "NewPipe Legacy Lightweight YouTube frontend for OS versions 4.x.\r\n\r\n**ATTENTION: If you are at version 0.18.6 and want to update, you must uninstall that version first.**\r\n\r\nNewPipe does not use any Google framework libraries, or the YouTube API. It only parses the website in order to gain the information it needs. Therefore this app can be used on devices without Google Services installed. Also, you don't need a YouTube account to use NewPipe, and it's FLOSS.",

**Comment by cweiske** [comment]
Thanks, merged.

I've got to wait for @Szeraax to sync the files to statics.ouya.world before I can deploy to my server.

**Pull request closed without merging**
