### PR TITLE
Games with missing dev Uuid

### PR DESCRIPTION
**Pull request by Szeraax**
How to help: Run `adb logcat` and go launch the game. May need to purchase something? Logcat will show the developer UUID. 

Go to the "classic" folder and find the corresponding packageName for the game and edit that file. Change the Devleoper UUID from 00000000-... to whatever was displayed by logcat.
Finally, remove the game from this 'games missing dev UUID' file so no one else goes looking for that game.

### CODE REVIEW

**Comment by cweiske** [comment]
Related to https://github.com/ouya-saviors/ouya-game-data/issues/14

**Comment by Stories8106** [comment]
Tried Joe Danger. It has IAP for currency that can be earned in game.  Upon attempting to use the in-game store, no hits for anything UUID related.  I have the notepad of the entire process if you want it. @cweiske

**Comment by Stories8106** [comment]
Wait, I think my CMD is cutting off after a certain amount.  Is there a way to override that?  I'm trying Miracle Fly now, and no hits for UUID, but I know I saw something on there flash across...

**Comment by Stories8106** [comment]
Super Puzzle Platformer Deluxe has no IAP.  It is a "Purchase only from store" game but if you can load it, it plays without checking for anything.  I'm like 90% on that.

**Comment by Stories8106** [comment]
Push the Fluffies has no IAP or Purchases

**Comment by Stories8106** [comment]
3D Checkers and 3D Reversi have no IAP

**Comment by cweiske** [comment]
Thansk for the info about that games - I've updated the game data. Joe Danger now has working products to buy, even if it says it cannot connect to the store at first.

**Comment by Stories8106** [comment]
Sent you an email with log files on the games that have IAP.  All the others are either purchase only, or have no IAP.  Take a look and let me know if you need anything else.  One of them is for issue #44

**Comment by cweiske** [comment]
We've got all now.

**Pull request closed without merging**
